name: CI-Lyra-Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Nuget.exe
        uses: nuget/setup-nuget@v2
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: '6.0.0'
      - name: Determine  GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.0.0
      - name: Prepare Version Info
        run: .\Prepare-VersionInfo.ps1 -Version ${{ steps.gitversion.outputs.semVer }}
        shell: powershell
      - name: Restore packages
        run: nuget restore Lyra2.sln
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2
      - name: Build with MSBuild
        run: msbuild Lyra2.sln -p:Configuration=Release
      - name: Create Archive
        run: .\Create-Release.ps1 -ReleaseName Lyra-Release-${{ steps.gitversion.outputs.semVer }}.zip
        shell: powershell
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./Lyra-Release-${{ steps.gitversion.outputs.semVer }}.zip
          asset_name: Lyra-Release-${{ steps.gitversion.outputs.semVer }}.zip
          asset_content_type: application/zip
